# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jow CI

on:
  push:
    branches: [jow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - run: npm ci
      - run: npm run build -- johannes-api
      - run: npm test -- johannes-api
